import turtle
fonte = turtle.Turtle()
fonte.setpos(100,-100)
fonte.shape("triangle")
monte = turtle.Turtle()
monte.left(60)
monte.forward(150)
monte.shape("square")
jonte = turtle.Turtle()
jonte.backward(150)
jonte.shape("circle")
monte.clear()
fonte.clear()
jonte.clear()
